##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := pin_exec

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := retire_test recover_test redirect_test exception_test illop_test

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=

###### Define the sanity subset ######

# This defines the list of tests that should run in sanity. It should include all the tests listed in
# TEST_TOOL_ROOTS and TEST_ROOTS excluding only unstable tests.
SANITY_SUBSET := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)

COMMON_LIB_PATH  := ../pin_lib
COMMON_LIB_CFILES   := $(wildcard $(COMMON_LIB_PATH)/*.cc)
COMMON_LIB_OBJFILES := $(patsubst $(COMMON_LIB_PATH)/%.cc,$(OBJDIR)%.o,$(COMMON_LIB_CFILES))

SOURCE_FILES := analysis_functions.cc globals.cc main_loop.cc exception_handling.cc scarab_interface.cc
SOURCE_OBJFILES := $(patsubst %.cc,$(OBJDIR)%.o,$(SOURCE_FILES))

SCARAB_DIR ?= ../../
#allow deprecated-declarations to enable compiling with newer PIN version e.g. 3.15 that define new APIs
TOOL_CXXFLAGS += -std=c++14 -g3 -static -I$(SCARAB_DIR) -Wno-error=deprecated-declarations
TOOL_LDFLAGS += -std=c++14

##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

.PHONY: commonlibs pin_exec debug_print debug_gdb debug

DEBUG_PRINT_FLAGS := -DDEBUG_PRINT=true
DEBUG_GDB_FLAGS := -O0

debug_print: TOOL_CXXFLAGS += $(DEBUG_PRINT_FLAGS)
debug_print: objects libs dlls apps tools

debug_gdb: TOOL_CXXFLAGS += $(DEBUG_GDB_FLAGS)
debug_gdb: objects libs dlls apps tools

debug: TOOL_CXXFLAGS += $(DEBUG_PRINT_FLAGS)
debug: TOOL_CXXFLAGS += $(DEBUG_GDB_FLAGS)
debug: objects libs dlls apps tools

pin_exec: $(OBJDIR)pin_exec.so

$(OBJDIR)%.o: $(COMMON_LIB_PATH)/%.cc
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< -DPIN_COMPILE

$(OBJDIR)%.o: %.cc
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< -DPIN_COMPILE

commonlibs: $(COMMON_LIB_OBJFILES)

# Build the tool as a dll (shared object).
# overriding rule in makefile.default.rules
$(OBJDIR)pin_exec$(PINTOOL_SUFFIX): $(OBJDIR)pin_exec$(OBJ_SUFFIX) $(SOURCE_OBJFILES) commonlibs
	$(info invoking link)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $< $(SOURCE_OBJFILES) $(COMMON_LIB_OBJFILES) $(TOOL_LPATHS) $(TOOL_LIBS)


$(OBJDIR)pin_exec$(OBJ_SUFFIX):pin_exec.cpp
	$(info invoking compile)
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< -MD -DPIN_COMPILE

-include $(OBJDIR)pin_exec.d