name: test-clang-format

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        exclude: './src/ramulator'
        extensions: 'h,cpp,cc,c'
        clangFormatVersion: 5
