name: make-release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Cache for Scarab Dependencies
      id: cache-scarab-dep
      uses: actions/cache@v1
      env:
        cache-name: cache-scarab-dep
      with:
        path: scarab-dependencies
        key: scarab-dep-key
        
    - name: Install Scarab Dependencies
      id: install-scarab
      if: steps.cache-scarab-dep.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        path: scarab-dependencies
        repository: hpsresearchgroup/scarab-dependencies
        token: ${{ secrets.HPS_ACCESS_TOKEN }}
      env:
        PIN_ROOT: $(pwd)/scarab-dependencies/pinplay-drdebug-3.5-pin-3.5-97503-gac534ca30-gcc-linux 
              
    - uses: actions/checkout@v2
      with:
        path: scarab
    - name: make release
      run: |
        make clean -C scarab/src
        make dbg -j -C scarab/src
        make opt -j -C scarab/src
      env:
        PIN_ROOT: ${{ github.workspace }}/scarab-dependencies/pinplay-drdebug-3.5-pin-3.5-97503-gac534ca30-gcc-linux

#    - name: test qsort
#      run: |
#        pip install -r scarab/bin/requirements.txt
#        cd scarab/utils/qsort; make; python3 scarab_test_qsort.py tmp
#      env:
#        PIN_ROOT: ${{ github.workspace }}/scarab-dependencies/pinplay-drdebug-3.5-pin-3.5-97503-gac534ca30-gcc-linux
